name: Build Android
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install npm dependencies
        run: npm

      - name: React Native Build
        uses: bamachoub/react-native-build-action@v1.0.0
        
      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease --stacktrace

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: android/app/build/outputs/apk/release/app-release.apk
 
