name: Build Android
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Set up Android SDK
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openjdk-8-jdk-headless
          wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O android-sdk.zip
          unzip -q android-sdk.zip -d android-sdk
          export ANDROID_SDK_ROOT=$PWD/android-sdk
          export PATH=$PATH:$PWD/android-sdk/tools/bin:$PWD/android-sdk/platform-tools

          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: android/app/build/outputs/apk/release/app-release.apk
